In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
data = pd.read_csv('nor.csv')  # 載入正規化後的資料
ydata = data['SALARY_CLASS']  # data y
xdata = data[['AGE', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%',
    '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB',
    'AST', 'STL', 'BLK', 'TOV', 'PF', 'POINTS', 'GP', 'MPG', 'ORPM',
    'DRPM', 'RPM', 'WINS_RPM', 'PIE', 'PACE', 'W']]  # data x
x = np.array(xdata)
y = np.array(ydata)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 335 entries, 0 to 334
Data columns (total 37 columns):
PLAYER             335 non-null object
TEAM               335 non-null object
POSITION           335 non-null object
AGE                335 non-null float64
FG                 335 non-null float64
FGA                335 non-null float64
FG%                335 non-null float64
3P                 335 non-null float64
3PA                335 non-null float64
3P%                335 non-null float64
2P                 335 non-null float64
2PA                335 non-null float64
2P%                335 non-null float64
eFG%               335 non-null float64
FT                 335 non-null float64
FTA                335 non-null float64
FT%                335 non-null float64
ORB                335 non-null float64
DRB                335 non-null float64
TRB                335 non-null float64
AST                335 non-null float64
STL                335 non-null float64
BLK               

In [2]:
skf = StratifiedKFold(n_splits=4, random_state=None, shuffle=True)  # 將資料按照label比例分出train data和test data(分成4種)
accuracy = 0  # 計算平均accuracy
trainDataLen = 0  # 計算平均train data大小
testDataLen = 0  # 計算平均test data大小
confusion = np.zeros([3,3])  # 計算平均confusion matrix
r = 1000  # range
for i in range(r):  # 計算1000 * 4次
    clf = GaussianNB()  # 使用NB model
    for train_index, test_index in skf.split(x, y):
        trainDataLen = trainDataLen + len(train_index)
        testDataLen = testDataLen + len(test_index)
        clf.fit(x[train_index], y[train_index])
        y_predict = clf.predict(x[test_index])
        accuracy = accuracy + accuracy_score(y[test_index], y_predict)
        confusion = confusion + confusion_matrix(y[test_index], y_predict)

In [3]:
print('trainDataLen:', trainDataLen/(r*4), 'testDataLen:', testDataLen/(r*4))
print('accuracy:', accuracy/(r*4))
print('confusion:\n', confusion/(r*4))

trainDataLen: 251.25 testDataLen: 83.75
accuracy: 0.5893331757445673
confusion:
 [[15.00025  4.006    0.74375]
 [13.84175 21.0255   7.63275]
 [ 1.129    7.03775 13.33325]]
