In [ ]:
#PG C SG 皆較高
#SF PF低==>有較多分類錯的球員

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

data = pd.read_csv('nor.csv')  # 載入正規化後的資料
ydata = data['SALARY_CLASS']  # data y
xdata = data[['AGE', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%',
    '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB',
    'AST', 'STL', 'BLK', 'TOV', 'PF', 'POINTS', 'GP', 'MPG', 'ORPM',
    'DRPM', 'RPM', 'WINS_RPM', 'PIE', 'PACE', 'W']]  # data x

In [2]:
position = ['PG', 'C', 'SF', 'SG', 'PF']
px = []
py = []
for p in position:
    a = xdata[data['POSITION'].isin([p])]
    a.reset_index(drop=True, inplace=True)
    b = ydata[data['POSITION'].isin([p])]
    b.reset_index(drop=True, inplace=True)
    px.append(np.array(a))
    py.append(np.array(b))

In [3]:
skf = StratifiedKFold(n_splits=5, random_state=None, shuffle=True)  # 將資料按照label比例分出train data和test data(分成5種)
r = 1000  # range
for i in range(len(position)):
    print('位置:', position[i])
    accuracy = 0  # 計算平均accuracy
    trainDataLen = 0  # 計算平均train data大小
    testDataLen = 0  # 計算平均test data大小
    confusion = np.zeros([3, 3])  # 計算平均confusion matrix
    for rr in range(r):
        clf = GaussianNB()  # 使用NB model
        for train_index, test_index in skf.split(px[i], py[i]):
            trainDataLen = trainDataLen + len(train_index)
            testDataLen = testDataLen + len(test_index)
            clf.fit(px[i][train_index], py[i][train_index])
            y_predict = clf.predict(px[i][test_index])
            accuracy = accuracy + accuracy_score(py[i][test_index], y_predict)
            confusion = confusion + confusion_matrix(py[i][test_index], y_predict)
    print('trainDataLen:', trainDataLen / (r * 5), 'testDataLen:', testDataLen / (r * 5))
    print('accuracy:', accuracy / (r * 5))
    print('confusion:\n', confusion / (r * 5))

位置: PG
trainDataLen: 54.4 testDataLen: 13.6
accuracy: 0.6660747619047518
confusion:
 [[2.6906 0.9094 0.    ]
 [1.5628 3.6624 1.1748]
 [0.     0.8876 2.7124]]
位置: C
trainDataLen: 52.8 testDataLen: 13.2
accuracy: 0.6233719780219736
confusion:
 [[1.035  0.7806 0.5844]
 [0.6642 4.6852 1.2506]
 [0.402  1.2988 2.4992]]
位置: SF
trainDataLen: 51.2 testDataLen: 12.8
accuracy: 0.5523544455544422
confusion:
 [[1.8944 0.9022 0.0034]
 [2.0782 3.0276 1.0942]
 [0.2124 1.4336 2.154 ]]
位置: SG
trainDataLen: 53.6 testDataLen: 13.4
accuracy: 0.6125739926739988
confusion:
 [[2.6148 0.611  0.3742]
 [1.318  4.2756 1.4064]
 [0.     1.4814 1.3186]]
位置: PF
trainDataLen: 55.2 testDataLen: 13.8
accuracy: 0.5244938095238099
confusion:
 [[2.6574e+00 5.4240e-01 2.0000e-04]
 [2.6894e+00 2.7752e+00 2.3354e+00]
 [0.0000e+00 9.8640e-01 1.8136e+00]]
