In [ ]:
#整體分類偏差
#其中C SF SG分類結果差

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

data = pd.read_csv('nor.csv')  # 載入正規化後的資料
ydata = data['SALARY_CLASS']  # data y
xdata = data[['AGE', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%',
    '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB',
    'AST', 'STL', 'BLK', 'TOV', 'PF', 'POINTS', 'GP', 'MPG', 'ORPM',
    'DRPM', 'RPM', 'WINS_RPM', 'PIE', 'PACE', 'W']]  # data x

In [2]:
position = ['PG', 'C', 'SF', 'SG', 'PF']
px = []
py = []
for p in position:
    a = xdata[data['POSITION'].isin([p])]
    a.reset_index(drop=True, inplace=True)
    b = ydata[data['POSITION'].isin([p])]
    b.reset_index(drop=True, inplace=True)
    px.append(np.array(a))
    py.append(np.array(b))

In [3]:
skf = StratifiedKFold(n_splits=5, random_state=None, shuffle=True)  # 將資料按照label比例分出train data和test data(分成5種)
r = 1000  # range
for i in range(len(position)):
    print('位置:', position[i])
    accuracy = 0  # 計算平均accuracy
    trainDataLen = 0  # 計算平均train data大小
    testDataLen = 0  # 計算平均test data大小
    confusion = np.zeros([3, 3])  # 計算平均confusion matrix
    for rr in range(r):
        clf = SVC()  # 使用svm model
        for train_index, test_index in skf.split(px[i], py[i]):
            trainDataLen = trainDataLen + len(train_index)
            testDataLen = testDataLen + len(test_index)
            clf.fit(px[i][train_index], py[i][train_index])
            y_predict = clf.predict(px[i][test_index])
            accuracy = accuracy + accuracy_score(py[i][test_index], y_predict)
            confusion = confusion + confusion_matrix(py[i][test_index], y_predict)
    print('trainDataLen:', trainDataLen / (r * 5), 'testDataLen:', testDataLen / (r * 5))
    print('accuracy:', accuracy / (r * 5))
    print('confusion:\n', confusion / (r * 5))


位置: PG
trainDataLen: 54.4 testDataLen: 13.6
accuracy: 0.5547899999999926
confusion:
 [[0.     3.6    0.    ]
 [0.     6.2044 0.1956]
 [0.     2.2948 1.3052]]
位置: C
trainDataLen: 52.8 testDataLen: 13.2
accuracy: 0.49564970695970234
confusion:
 [[0.     2.3918 0.0082]
 [0.     6.5056 0.0944]
 [0.     4.1764 0.0236]]
位置: SF
trainDataLen: 51.2 testDataLen: 12.8
accuracy: 0.48880599400601843
confusion:
 [[0.     2.8    0.    ]
 [0.     6.0764 0.1236]
 [0.     3.6416 0.1584]]
位置: SG
trainDataLen: 53.6 testDataLen: 13.4
accuracy: 0.5243589743589641
confusion:
 [[0.  3.6 0. ]
 [0.  7.  0. ]
 [0.  2.8 0. ]]
位置: PF
trainDataLen: 55.2 testDataLen: 13.8
accuracy: 0.5661904761904729
confusion:
 [[0.  3.2 0. ]
 [0.  7.8 0. ]
 [0.  2.8 0. ]]
