In [1]:
import pandas as pd
import re
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
data = pd.read_csv('googleplaystore_preprocess.csv')
data
# data.to_csv('data.csv', sep=",", index=0)

App        Category  \
0                                          Paint Splash!  ART_AND_DESIGN   
1                                 Test Application DT 02  ART_AND_DESIGN   
2                   Fantasy theme dark bw black building  ART_AND_DESIGN   
3                           Sad Poetry Photo Frames 2018  ART_AND_DESIGN   
4                              Anime Manga Coloring Book  ART_AND_DESIGN   
5                                     Easy Origami Ideas  ART_AND_DESIGN   
6                         PIP Camera - PIP Collage Maker  ART_AND_DESIGN   
7                Name Art Photo Editor - Focus n Filters  ART_AND_DESIGN   
8              Boys Photo Editor - Six Pack & Men's Suit  ART_AND_DESIGN   
9            Popsicle Sticks and Similar DIY Craft Ideas  ART_AND_DESIGN   
10                                   Coloring book moana  ART_AND_DESIGN   
11                           Logo Maker - Small Business  ART_AND_DESIGN   
12                         Drawing Clothes Fashion Ideas  ART_AND_DESIGN   
13                              350 Diy Room Decor Ideas  ART_AND_DESIGN   
14        Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN   
15               Smoke Effect Photo Maker - Smoke Editor  ART_AND_DESIGN   
16                       Learn To Draw Kawaii Characters  ART_AND_DESIGN   
17                 Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN   
18               Spring flowers theme couleurs d t space  ART_AND_DESIGN   
19                        Tattoo Name On My Photo Editor  ART_AND_DESIGN   
20                                 Mandala Coloring Book  ART_AND_DESIGN   
21                           HD Mickey Minnie Wallpapers  ART_AND_DESIGN   
22        UNICORN - Color By Number & Pixel Art Coloring  ART_AND_DESIGN   
23     Canva: Poster, banner, card maker & graphic de...  ART_AND_DESIGN   
24                                 Sketch - Draw & Paint  ART_AND_DESIGN   
25                         Colorfit - Drawing & Coloring  ART_AND_DESIGN   
26                               AJ Styles HD Wallpapers  ART_AND_DESIGN   
27     Install images with music to make video withou...  ART_AND_DESIGN   
28                               Text on Photo - Fonteee  ART_AND_DESIGN   
29                                      Infinite Painter  ART_AND_DESIGN   
...                                                  ...             ...   
10674                               Weather Forecast Pro         WEATHER   
10675                       APE Weather ( Live Forecast)         WEATHER   
10676                              Wetter by t-online.de         WEATHER   
10677                                       AEMET's time         WEATHER   
10678                         weather - weather forecast         WEATHER   
10679  The Weather Channel: Rain Forecast & Storm Alerts         WEATHER   
10680  AccuWeather: Daily Forecast & Live Weather Rep...         WEATHER   
10681    Weather by WeatherBug: Forecast, Radar & Alerts         WEATHER   
10682                         MyRadar NOAA Weather Radar         WEATHER   
10683                                       SMHI Weather         WEATHER   
10684                                      Yahoo Weather         WEATHER   
10685                           Rainfall radar - weather         WEATHER   
10686  Yahoo! Weather for SH Forecast for understandi...         WEATHER   
10687                                The Weather Network         WEATHER   
10688   GO Weather - Widget, Theme, Wallpaper, Efficient         WEATHER   
10689                                Weather From DMI/YR         WEATHER   
10690    Storm Radar: Tornado Tracker & Hurricane Alerts         WEATHER   
10691                                     Yandex.Weather         WEATHER   
10692                                        HTC Weather         WEATHER   
10693                             Weather by eltiempo.es         WEATHER   
10694          Climatempo Lite - 15 day weather forecast         WEATHER   
10695                    

In [2]:
data['Category'].unique()

array(['ART_AND_DESIGN', 'AUTO_AND_VEHICLES', 'BEAUTY',
       'BOOKS_AND_REFERENCE', 'BUSINESS', 'COMICS', 'COMMUNICATION',
       'DATING', 'EDUCATION', 'ENTERTAINMENT', 'EVENTS', 'FAMILY',
       'FINANCE', 'FOOD_AND_DRINK', 'GAME', 'HEALTH_AND_FITNESS',
       'HOUSE_AND_HOME', 'LIBRARIES_AND_DEMO', 'LIFESTYLE',
       'MAPS_AND_NAVIGATION', 'MEDICAL', 'NEWS_AND_MAGAZINES',
       'PARENTING', 'PERSONALIZATION', 'PHOTOGRAPHY', 'PRODUCTIVITY',
       'SHOPPING', 'SOCIAL', 'SPORTS', 'TOOLS', 'TRAVEL_AND_LOCAL',
       'VIDEO_PLAYERS', 'WEATHER'], dtype=object)

In [3]:
le = preprocessing.LabelEncoder()
newCategory = le.fit_transform(data['Category'])

In [4]:
data['Size'].unique()

array(['1.2M', '1.9M', '10M', '11M', '12M', '14M', '15M', '17M', '19M',
       '2.7M', '2.8M', '2.9M', '20M', '21M', '23M', '24M', '25M', '26M',
       '28M', '29M', '3.1M', '3.5M', '3.6M', '3.7M', '31M', '33M', '37M',
       '39M', '4.2M', '4.4M', '4.5M', '4.6M', '5.2M', '5.5M', '5.6M',
       '5.9M', '6.0M', '6.1M', '7.0M', '7.7M', '7.9M', '8.0M', '8.2M',
       '8.6M', '8.7M', '9.2M', '9.4M', 'Varies with device', '1.1M',
       '1.7M', '13M', '16M', '18M', '2.2M', '2.4M', '2.5M', '201k', '27M',
       '3.4M', '3.9M', '32M', '34M', '35M', '38M', '4.8M', '42M', '48M',
       '5.4M', '5.7M', '54M', '56M', '57M', '58M', '6.3M', '6.5M', '6.6M',
       '66M', '8.4M', '8.9M', '885k', '88M', '9.0M', '97M', '2.6M', '22M',
       '3.2M', '30M', '52M', '6.4M', '6.7M', '7.1M', '7.4M', '9.8M',
       '9.9M', '1.4M', '1.5M', '1.6M', '2.1M', '2.3M', '3.0M', '3.3M',
       '4.0M', '4.1M', '4.3M', '4.7M', '4.9M', '41M', '44M', '45M', '49M',
       '5.0M', '5.1M', '5.3M', '50M', '51M', '6.8M', '6.9M

In [5]:
# 0<=10M；1<=100M；2為Varies with device
newSize = []
for i in range(len(data['Size'])):
    if data['Size'][i][-1] == 'M':
        if float(data['Size'][i][0:-1]) <= 10:
            newSize.append(0)
        elif float(data['Size'][i][0:-1]) <= 100:
            newSize.append(1)
    elif data['Size'][i][-1] == 'k':
        newSize.append(0)
    elif data['Size'][i][-1] == 'e':
        newSize.append(2)
print(newSize.count(0))
print(newSize.count(1))
print(newSize.count(2))

4021
5007
1676


In [6]:
data['Installs'].unique()

array(['100,000+', '0+', '5,000+', '10,000+', '1,000,000+', '500,000+',
       '50,000+', '100+', '10,000,000+', '50,000,000+', '1,000+',
       '5,000,000+', '10+', '50+', '500+', '5+', '1+', '100,000,000+',
       '1,000,000,000+', '500,000,000+', '0'], dtype=object)

In [7]:
import re
newInstall = []
r = '[’!"#$%&\'()*+,-./:;<=>?@，。?★、…【】《》？“”‘’！[\\]^_`{|}~]+' #要去除的符號
for i in range(len(data['Installs'])):
    temp = int(re.sub(r, "", data['Installs'][i]))#去除符號
    if temp <= 10000:
        newInstall.append(0)
    elif temp <= 1000000:
        newInstall.append(1)
    else:
        newInstall.append(2)
print(newInstall.count(0))
print(newInstall.count(1))
print(newInstall.count(2))

4197
3707
2800


In [8]:
data['Price'].unique()

array(['0', '$1.99', '$1.49', '$9.99', '$3.08', '$1.96', '$4.49', '$5.99',
       '$5.49', '$6.49', '$2.99', '$0.99', '$3.61', '$4.60', '$3.99',
       '$1.75', '$89.99', '$2.49', '$19.90', '$17.99', '$4.99', '$8.99',
       '$12.99', '$2.90', '$19.99', '$7.99', '$6.99', '$109.99', '$10.00',
       '$13.99', '$2.00', '$399.99', '$1.04', '$39.99', '$14.99', '$1.26',
       '$4.84', '$389.99', '$19.40', '$1.59', '$46.99', '$1.20', '$4.77',
       '$29.99', '$7.49', '$394.99', '$28.99', '$18.99', '$30.99',
       '$3.49', '$16.99', '$1.61', '$14.00', '$3.04', '$37.99', '$299.99',
       '$379.99', '$400.00', '$11.99', '$15.99', '$9.00', '$1.50',
       '$1.00', '$15.46', '$24.99', '$10.99', '$74.99', '$200.00',
       '$79.99', '$33.99', '$5.00', '$4.59', '$4.85', '$1.70', '$3.95',
       '$1.29', '$2.60', '$4.29', '$8.49', '$154.99', '$3.02', '$3.88',
       '$4.80', '$25.99', '$2.59', '$3.28', '$1.76', '$1.97', '$2.50',
       '$3.90', '$2.95', '$2.56'], dtype=object)

In [9]:
# 0:0；1=the other
newPrice = []
r2 = '[’!"#$%&\'()*+,-/:;<=>?@，。?★、…【】《》？“”‘’！[\\]^_`{|}~]+' #要去除的符號
for i in range(len(data['Price'])):
    temp = int(re.sub(r2, "", data['Price'][i]))#去除符號
    if temp == 0:
        newPrice.append(0)
    else:
        newPrice.append(1)
print(newPrice.count(0))
print(newPrice.count(1))
    

9917
787


In [10]:
data['Content Rating'].unique()

array(['Everyone', 'Teen', 'Everyone 10+', 'Mature 17+',
       'Adults only 18+', 'Unrated'], dtype=object)

In [11]:
le = preprocessing.LabelEncoder()
newRate = le.fit_transform(data['Content Rating'])
print(newRate)

[1 1 1 ... 1 1 1]


In [12]:
newDate = []
for i in data['Last Updated']:
    if int(i[-2:]) == 18:
        newDate.append(0)
    elif int(i[-2:]) == 17:
        newDate.append(1)
    else:
        newDate.append(2)
print(newDate.count(0))
print(newDate.count(1))
print(newDate.count(2))

7256
1839
1609


In [13]:
data['Android Ver'].unique()

array(['4.1 and up', '4.2 and up', '4.0 and up', '4.0.3 and up',
       '2.3 and up', '4.4 and up', '3.0 and up', '5.0 and up',
       '2.3.3 and up', 'Varies with device', '6.0 and up', '2.2 and up',
       '3.2 and up', '4.4W and up', '4.3 and up', '1.6 and up',
       '2.1 and up', '1.0 and up', '5.1 and up', '1.5 and up',
       '7.0 and up', '2.0 and up', '5.0 - 7.1.1', '4.0.3 - 7.1.1',
       '2.0.1 and up', '3.1 and up', '2.2 - 7.1.1', '8.0 and up',
       '7.1 and up', '7.0 - 7.1.1', '5.0 - 6.0', '5.0 - 8.0',
       '4.1 - 7.1.1'], dtype=object)

In [14]:
newVer = []
dic = {}
for i in data['Android Ver']:
    if i[0] == 'V':
        newVer.append(3)
    elif i[0] == '1' or i[0] == '2':
        newVer.append(0)
    elif i[0] == '3' or i[0] == '4':
        newVer.append(1)
    elif i[0] == '5' or i[0] == '6' or i[0] == '7' or i[0] == '8':
        newVer.append(2)
print(newVer.count(0))
print(newVer.count(1))
print(newVer.count(2))
print(newVer.count(3))

1477
7154
724
1349


In [15]:
df = pd.DataFrame(list(zip(newCategory,newSize,newInstall,newPrice,newRate,newDate,newVer)),columns = ['Category', 'Size', 'install', 'price', 'rate', 'date', 'ver'])

In [16]:
y = df['install']
X = df.drop(columns=['install'])

In [17]:
scale = preprocessing.MinMaxScaler()
X = pd.DataFrame(scale.fit_transform(X),columns=X.keys())

In [18]:
#SVM model
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
SVM = SVC(kernel='linear')

In [19]:
#Gaussian NB model
from sklearn.naive_bayes import GaussianNB
clf_gnb = GaussianNB()

In [20]:
#Decision Tree model
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier(max_depth=None,criterion='entropy')

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
SVM.fit(X_train, y_train)
y_pred = SVM.predict(X_test)

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print('Original on SVM')

[[501 185 114]
 [315 255 219]
 [ 68 183 301]]
              precision    recall  f1-score   support

           0       0.57      0.63      0.60       800
           1       0.41      0.32      0.36       789
           2       0.47      0.55      0.51       552

    accuracy                           0.49      2141
   macro avg       0.48      0.50      0.49      2141
weighted avg       0.49      0.49      0.49      2141

Original on SVM


In [22]:
clf_gnb.fit(X_train, y_train)
y_pred = clf_gnb.predict(X_test)

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print('Original on NB')

[[350  21 429]
 [188  24 577]
 [ 30  13 509]]
              precision    recall  f1-score   support

           0       0.62      0.44      0.51       800
           1       0.41      0.03      0.06       789
           2       0.34      0.92      0.49       552

    accuracy                           0.41      2141
   macro avg       0.46      0.46      0.35      2141
weighted avg       0.47      0.41      0.34      2141

Original on NB


In [23]:
dtree.fit(X_train, y_train)
y_pred = dtree.predict(X_test)

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print('Original on D-tree')

[[574 193  33]
 [325 339 125]
 [ 85 154 313]]
              precision    recall  f1-score   support

           0       0.58      0.72      0.64       800
           1       0.49      0.43      0.46       789
           2       0.66      0.57      0.61       552

    accuracy                           0.57      2141
   macro avg       0.58      0.57      0.57      2141
weighted avg       0.57      0.57      0.57      2141

Original on D-tree


In [24]:
from sklearn.decomposition import PCA
pca = PCA(n_components=3)

newX1 = pca.fit_transform(X)
X_train2, X_test2, y_train2, y_test2= train_test_split(newX1, y, test_size=0.2, random_state=42)

SVM.fit(X_train2, y_train2)
y_pred2 = SVM.predict(X_test2)

print(confusion_matrix(y_test2,y_pred2))
print(classification_report(y_test2,y_pred2))
print('after PCA on SVM')

[[676  97  27]
 [512 175 102]
 [216 116 220]]
              precision    recall  f1-score   support

           0       0.48      0.84      0.61       800
           1       0.45      0.22      0.30       789
           2       0.63      0.40      0.49       552

    accuracy                           0.50      2141
   macro avg       0.52      0.49      0.47      2141
weighted avg       0.51      0.50      0.46      2141

after PCA on SVM


In [25]:
clf_gnb.fit(X_train2, y_train2)
y_pred2 = clf_gnb.predict(X_test2)

print(confusion_matrix(y_test2,y_pred2))
print(classification_report(y_test2,y_pred2))
print('after PCA on NB')

[[593 161  46]
 [399 258 132]
 [109 203 240]]
              precision    recall  f1-score   support

           0       0.54      0.74      0.62       800
           1       0.41      0.33      0.37       789
           2       0.57      0.43      0.49       552

    accuracy                           0.51      2141
   macro avg       0.51      0.50      0.49      2141
weighted avg       0.50      0.51      0.50      2141

after PCA on NB


In [26]:
dtree.fit(X_train2, y_train2)
y_pred2 = dtree.predict(X_test2)

print(confusion_matrix(y_test2,y_pred2))
print(classification_report(y_test2,y_pred2))
print('after PCA on D-tree')

[[570 197  33]
 [323 338 128]
 [ 80 155 317]]
              precision    recall  f1-score   support

           0       0.59      0.71      0.64       800
           1       0.49      0.43      0.46       789
           2       0.66      0.57      0.62       552

    accuracy                           0.57      2141
   macro avg       0.58      0.57      0.57      2141
weighted avg       0.57      0.57      0.57      2141

after PCA on D-tree


In [27]:
from sklearn.decomposition import NMF
nmf = NMF(n_components=3, solver="cd")

newX2 = nmf.fit_transform(X)
X_train3, X_test3, y_train3, y_test3 = train_test_split(newX2, y, test_size=0.2, random_state=42)

SVM.fit(X_train3, y_train3)
y_pred3 = SVM.predict(X_test3)

print(confusion_matrix(y_test3,y_pred3))
print(classification_report(y_test3,y_pred3))
print('after NMF on SVM')

[[748  25  27]
 [653  36 100]
 [316  15 221]]
              precision    recall  f1-score   support

           0       0.44      0.94      0.59       800
           1       0.47      0.05      0.08       789
           2       0.64      0.40      0.49       552

    accuracy                           0.47      2141
   macro avg       0.51      0.46      0.39      2141
weighted avg       0.50      0.47      0.38      2141

after NMF on SVM


In [28]:
clf_gnb.fit(X_train3, y_train3)
y_pred3 = clf_gnb.predict(X_test3)

print(confusion_matrix(y_test3,y_pred3))
print(classification_report(y_test3,y_pred3))
print('after NMF on NB')

[[576  73 151]
 [388 100 301]
 [101  61 390]]
              precision    recall  f1-score   support

           0       0.54      0.72      0.62       800
           1       0.43      0.13      0.20       789
           2       0.46      0.71      0.56       552

    accuracy                           0.50      2141
   macro avg       0.48      0.52      0.46      2141
weighted avg       0.48      0.50      0.45      2141

after NMF on NB


In [29]:
dtree.fit(X_train3, y_train3)
y_pred3 = dtree.predict(X_test3)

print(confusion_matrix(y_test3,y_pred3))
print(classification_report(y_test3,y_pred3))
print('after NMF on D-tree')

[[574 192  34]
 [323 340 126]
 [ 83 153 316]]
              precision    recall  f1-score   support

           0       0.59      0.72      0.64       800
           1       0.50      0.43      0.46       789
           2       0.66      0.57      0.61       552

    accuracy                           0.57      2141
   macro avg       0.58      0.57      0.57      2141
weighted avg       0.57      0.57      0.57      2141

after NMF on D-tree


In [30]:
from sklearn.decomposition import TruncatedSVD
svd = TruncatedSVD(n_components=3)

newX3 = svd.fit_transform(X)
X_train4, X_test4, y_train4, y_test4 = train_test_split(newX3, y, test_size=0.2, random_state=42)

SVM.fit(X_train4, y_train4)
y_pred4 = SVM.predict(X_test4)

print(confusion_matrix(y_test4,y_pred4))
print(classification_report(y_test4,y_pred4))
print('after SVD on SVM')

[[750  23  27]
 [653  36 100]
 [317  14 221]]
              precision    recall  f1-score   support

           0       0.44      0.94      0.60       800
           1       0.49      0.05      0.08       789
           2       0.64      0.40      0.49       552

    accuracy                           0.47      2141
   macro avg       0.52      0.46      0.39      2141
weighted avg       0.51      0.47      0.38      2141

after SVD on SVM


In [31]:
clf_gnb.fit(X_train4, y_train4)
y_pred4 = clf_gnb.predict(X_test4)

print(confusion_matrix(y_test4,y_pred4))
print(classification_report(y_test4,y_pred4))
print('after SVD on NB')

[[573 172  55]
 [383 249 157]
 [100 185 267]]
              precision    recall  f1-score   support

           0       0.54      0.72      0.62       800
           1       0.41      0.32      0.36       789
           2       0.56      0.48      0.52       552

    accuracy                           0.51      2141
   macro avg       0.50      0.51      0.50      2141
weighted avg       0.50      0.51      0.50      2141

after SVD on NB


In [32]:
dtree.fit(X_train4, y_train4)
y_pred4 = dtree.predict(X_test4)

print(confusion_matrix(y_test4,y_pred4))
print(classification_report(y_test4,y_pred4))
print('after SVD on D-tree')

[[576 190  34]
 [320 342 127]
 [ 84 153 315]]
              precision    recall  f1-score   support

           0       0.59      0.72      0.65       800
           1       0.50      0.43      0.46       789
           2       0.66      0.57      0.61       552

    accuracy                           0.58      2141
   macro avg       0.58      0.57      0.57      2141
weighted avg       0.57      0.58      0.57      2141

after SVD on D-tree


In [33]:
#Autoencoder
from keras.models import Model
from keras.layers import Dense, Input
#X_train6 #(8563,6)
#y_train6 #(8563,)

input_dim = 6
encoding_dim = 3
# encoder layers
input_data = Input(shape=(input_dim,))
# encoder = Dense(input_dim, activation='tanh')(input_data)
encoder_output = Dense(encoding_dim,activation='tanh')(input_data)

# decoder layers
# decoder = Dense(encoding_dim, activation='tanh')(encoder_output)
decoder = Dense(input_dim, activation='tanh')(encoder_output)

autoencoder = Model(inputs=input_data,outputs=decoder)
encoder = Model(inputs=input_data, output=encoder_output)

print(autoencoder.summary())

autoencoder.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
history = autoencoder.fit(X, X, epochs=10, verbose=1, batch_size=32, shuffle=True)
AE_X = encoder.predict(X)

C:\Users\user\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=Tensor("in..., outputs=Tensor("de...)`


Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 6)                 0         
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 21        
_________________________________________________________________
dense_2 (Dense)              (None, 6)                 24        
Total params: 45
Trainable params: 45
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/10
10704/10704 [==============================] - 0s 32us/step - loss: 11.6044 - accuracy: 0.3644
Epoch 2/10
10704/10704 [==============================] - 0s 28us/step - loss: 11.3493 - accuracy: 0.3154
Epoch 3/10
10704/10704 [==============================] - 0s 25us/step - loss: 13.2726 - accuracy: 0.3163
Epoch 4/10
10704/10704 [==============================] - 0s 27us/step

In [34]:
X_train5, X_test5, y_train5, y_test5 = train_test_split(AE_X, y, test_size=0.2, random_state=42)
SVM.fit(X_train5, y_train5)
y_pred5 = SVM.predict(X_test5)

print(confusion_matrix(y_test5,y_pred5))
print(classification_report(y_test5,y_pred5))
print('after Autoencoder on SVM')

[[527 238  35]
 [388 289 112]
 [105 223 224]]
              precision    recall  f1-score   support

           0       0.52      0.66      0.58       800
           1       0.39      0.37      0.38       789
           2       0.60      0.41      0.49       552

    accuracy                           0.49      2141
   macro avg       0.50      0.48      0.48      2141
weighted avg       0.49      0.49      0.48      2141

after Autoencoder on SVM


In [35]:
clf_gnb.fit(X_train5, y_train5)
y_pred5 = clf_gnb.predict(X_test5)

print(confusion_matrix(y_test5,y_pred5))
print(classification_report(y_test5,y_pred5))
print('after Autoencoder on NB')

[[475 127 198]
 [329 114 346]
 [ 83  51 418]]
              precision    recall  f1-score   support

           0       0.54      0.59      0.56       800
           1       0.39      0.14      0.21       789
           2       0.43      0.76      0.55       552

    accuracy                           0.47      2141
   macro avg       0.45      0.50      0.44      2141
weighted avg       0.46      0.47      0.43      2141

after Autoencoder on NB


In [36]:
dtree.fit(X_train5, y_train5)
y_pred5 = dtree.predict(X_test5)

print(confusion_matrix(y_test5,y_pred5))
print(classification_report(y_test5,y_pred5))
print('after Autoencoder on D-tree')

[[574 193  33]
 [328 335 126]
 [ 82 157 313]]
              precision    recall  f1-score   support

           0       0.58      0.72      0.64       800
           1       0.49      0.42      0.45       789
           2       0.66      0.57      0.61       552

    accuracy                           0.57      2141
   macro avg       0.58      0.57      0.57      2141
weighted avg       0.57      0.57      0.57      2141

after Autoencoder on D-tree
